package net.smartgst.returns.gstr1;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.JsonNode;
import com.mashape.unirest.http.Unirest;
import net.smartgst.auth.AESEncryption;
import net.smartgst.auth.GSTAuth;
import net.smartgst.returns.gstr1.data.*;
import org.apache.commons.codec.digest.DigestUtils;
import org.bouncycastle.crypto.Digest;
import org.bouncycastle.crypto.digests.SHA256Digest;
import org.bouncycastle.crypto.macs.HMac;
import org.bouncycastle.crypto.params.KeyParameter;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.json.JSONObject;

import javax.crypto.Mac;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;
import java.io.InputStream;
import java.io.StringWriter;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Date;
import java.util.UUID;

/**
 * Created by gowthaman on 27/11/16.
 */
public class Main {

    //random User Name
    private static final String USER_NAME = UUID.randomUUID().toString();
    //random Trx Id
    private static final String TXN = UUID.randomUUID().toString();

    //hard coded state code
    private static final String STATE_CD = "11";

    private static final String CLIENT_ID = "l7xx6df7496552824f15b7f4523c0a1fc114";
    private static final String CLIENT_SECRET = "f328fe52752349c893aa93adcffed8f5";


    //hard coded OTP
    private static final String OTP = "102030";

    //hard coded for now
    private static final String IP_USR = "192.168.1.1";


    public static void main(String[] args) throws Exception {
        InputStream pubKeyInpStream = Thread.currentThread().getContextClassLoader().getResourceAsStream("GSTN_PublicKey.cer");


        gstAuth = new GSTAuth(
                CLIENT_ID, CLIENT_SECRET,
                USER_NAME, STATE_CD, IP_USR,
                TXN, pubKeyInpStream);

        if (gstAuth.otpRequest()) {
            System.out.println("OTP Request Success");
            if (gstAuth.authTokenRequest(OTP)) {
                System.out.println("Auth Token Success");


                GSTR1 gstr1 = new GSTR1();
                gstr1.gstin = "25ABCDE1028F6Z4";
                //todo replace with Non Deprecated function
                gstr1.financialPeriod = new Date(2016, 5, 1);
                gstr1.prevYearGrossTurnOver = 1015000.00;

                InvLineItem li = new InvLineItem();
                li.slNo = 1;
                li.action = null;
                li.goodsOrService = GoodsService.SERVICE;
                li.goodsOrServiceCode = "S1991";
                li.taxableValue = 1000;
                li.igstRate = 5.0;
                li.igstAmt = 50.0;

                li.cgstRate = 5.0;
                li.cgstAmt = 50.0;

                li.sgstRate = 5.0;
                li.sgstAmt = 50.0;


                Invoice i = new Invoice();
                i.checkSum = ""; //will be generated by GST System
                i.items = new ArrayList<InvLineItem>() {{
                    add(li);
                }};

                i.supplierInvNum = "INV001";
                i.supplierInvDt = new Date();
                i.supplierInvVal = 1150.00;
                i.pos = "01";
                i.reverseCharge = false;
                i.provisionalAssessment = true;


                B2B b2b = new B2B();
                b2b.partyGSTIN = "21ABCDE3180F8Z6";
                b2b.invoices = new ArrayList<Invoice>() {{
                    add(i);
                }};
                gstr1.b2b = new ArrayList<B2B>() {{
                    add(b2b);
                }};

                postGstr1(gstr1);
            }
        }

    }

    private static GSTAuth gstAuth;
    private static final ObjectMapper objectMapper = new ObjectMapper();
    private static final String BASE_URL = "http://devapi.gstsystem.co.in";
    private static final String GSTR1_PATH = "/taxpayerapi/v0.1/returns/gstr1";
    private static final String APPLICATION_JSON = "application/json";

    private static boolean postGstr1(GSTR1 gstr1) throws Exception {
        //actual payload
        String json = objectMapper.writeValueAsString(gstr1);
        AESEncryption aesEncryption = gstAuth.getAesEncryption();

        //convery payload to Base64
        byte[] jsonBase64 = Base64.getEncoder().encode(json.getBytes());

        //encrypt the Base64 data
        String encryptedPayload = aesEncryption.encryptEK(jsonBase64, gstAuth.getAuthSEK());


        //create hmac
        HMac hmac = new HMac(new SHA256Digest());
        byte[] resBuf = new byte[hmac.getMacSize()];

        //init with the AuthSEK
        hmac.init(new KeyParameter(gstAuth.getAuthSEK()));
        //add the json(Base64)
        hmac.update(jsonBase64, 0, jsonBase64.length);
        hmac.doFinal(resBuf, 0);


        JSONObject object = new JSONObject();
        object.put("action", "RETSAVE");
        object.put("data", encryptedPayload);

        //send hmac in base64 string format
        object.put("hmac", new String(Base64.getEncoder().encode(resBuf)));

        System.out.println(object.toString());

        HttpResponse<JsonNode> resp = Unirest.put(String.format("%s/%s", BASE_URL, GSTR1_PATH))
                .header("Content-Type", APPLICATION_JSON)
                .header("state-cd", STATE_CD)
                .header("clientid", CLIENT_ID)
                .header("client-secret", CLIENT_SECRET)
                .header("ip-usr", IP_USR)
                .header("username", USER_NAME)
                .header("auth-token", gstAuth.getAuthToken())
                .header("appkey", gstAuth.getAppKeyEncryptedAndCoded())
                .header("txn", TXN)
                .body(new JsonNode(object.toString()))
                .asJson();

        System.out.println(resp.getStatus());
        System.out.println(resp.getBody());

        JSONObject gstrRespObj = resp.getBody().getObject();
        String data = gstrRespObj.getString("data");
        String rek = gstrRespObj.getString("rek");

        //recover apiEncryptionKey from Response using our AuthSEK
        byte[] apiEK = aesEncryption.decrypt(rek, gstAuth.getAuthSEK());

        //using the apiEncryptionKey, recover the Json data (in base64 fmt)
        String respJsoninBase64 = new String(aesEncryption.decrypt(data, apiEK));

        //convert base64 to original json (in bytes)
        byte[] respJsonInBytes = aesEncryption.decodeBase64StringTOByte(respJsoninBase64);

        //convery original json in bytes to json string
        String jsonData = new String(respJsonInBytes);
        System.out.println(jsonData);

        return false;
    }

}


